#server:
#  port: 9101

feign:
  hystrix:
    enabled: true

spring:
  application:
    name: myshop-user
  datasource:
    url: jdbc:mysql://192.168.232.136:3307/springcloud?characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 893640
  jpa:
    show-sql: true # 是否打印sql语句
    generate-ddl: true # 是否自动建表
    database: mysql # jpa连接的数据库类型
  rabbitmq:
    host: 192.168.232.136
  cloud:
    config:
      name: user
      profile: dev
      label: main
      discovery:
        enabled: true
        service-id: myshop-config

eureka:
  client:
    register-with-eureka: true # 作为客户端需要注册到Eureka
    fetch-registry: true  # 作为客户端需要从Eureka获取注册信息
    service-url: # 客户端注册地址
      defaultZone: http://localhost:8888/eureka
  instance:
    # 优先使用该服务的IP地址注册到Eureka，在生产环境建议改为true
    prefer-ip-address: true

myshop-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule